### ISSUE TITLE
More details than "path not found"

### ISSUE THREAD

**Issue by cheryly279** [kubetail-org/loadjs#110]
Is there some way of determining why we ended up in the error callback? The documentation makes it seem like it's just thought of as the path was not found, but what if there was some other reason the library couldn't load? For instance, what if there was a 429 response code indicating a rate limiter had been hit?

**Comment by amorey** [comment]
This library loads files via the `<script>` tag in order to enable cross-domain requests but the downside is that it can't access the response code. If you load files with an `XMLHttpRequest` or `fetch()` call you'll be able to access the HTTP response but only for same-site requests or cross-site requests with CORS enabled.

**Comment by cheryly279** [comment]
Ah I see, thanks!
